version: "3.9"

services:
  streamlit:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501
    restart: unless-stopped
